### ISSUE TITLE
Update TypeScript exports to support moduleResolution bundler

### ISSUE THREAD

**Issue by kwangure** [lezer-parser/html#9]
[`moduleResolution: "bundler"`](https://www.typescriptlang.org/tsconfig#moduleResolution) is a recent setting added to TypeScript to support bundler setups. It's the setting you should probably be using when bundling code. With this setting TypeScript only searches for types in the exports field of the `package.json`.

It requires the following change:

```diff
 "exports": {
   "import": "./dist/index.js",
   "require": "./dist/index.cjs",
+  "types": "./dist/index.d.ts"
 },
```

**Comment by marijnh** [comment]
Should already work as of 426fe0428187967a07597aa7f0dd00e9aec5e4fc
